version: "3.9"
services:
  signaling:
    build:
      context: .
      dockerfile: apps/signaling/Dockerfile
    env_file:
      - .env
    environment:
      - PORT=${SIGNALING_PORT}
      - PIN_LENGTH=${PIN_LENGTH}
      - SESSION_TTL_SECONDS=${SESSION_TTL_SECONDS}
      - ICE_SERVERS=${ICE_SERVERS}
    ports:
      - "${SIGNALING_PORT}:8080"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_BASE_PATH: ${NEXT_BASE_PATH}
        NEXT_PUBLIC_SIGNALING_URL: ${NEXT_PUBLIC_SIGNALING_URL}
        PUBLIC_WS_URL: ${PUBLIC_WS_URL}
        NEXT_PUBLIC_ICE_SERVERS: ${NEXT_PUBLIC_ICE_SERVERS}
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_SIGNALING_URL=${NEXT_PUBLIC_SIGNALING_URL:-${PUBLIC_WS_URL}}
      - NEXT_PUBLIC_ICE_SERVERS=${NEXT_PUBLIC_ICE_SERVERS:-${ICE_SERVERS}}
      - NEXT_BASE_PATH=${NEXT_BASE_PATH}
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - signaling
    restart: unless-stopped

networks:
  default:
    driver: bridge